import { createContext, useContext, useState } from 'react'

export const LANGUAGES = [
  { code: 'en', label: 'EN',    name: 'English'  },
  { code: 'te', label: 'తె',   name: 'Telugu'   },
  { code: 'kn', label: 'ಕ',    name: 'Kannada'  },
  { code: 'ta', label: 'த',    name: 'Tamil'    },
  { code: 'hi', label: 'हि',   name: 'Hindi'    },
]

export const STRINGS = {
  en: {
    greeting:         (name) => `Namaskaram, ${name} 🙏`,
    tagline:          'Reputation management for local businesses',
    signIn:           'Sign In',
    signOut:          'Sign Out',
    getStarted:       'Get Started',
    email:            'Email address',
    password:         'Password',
    noAccount:        "Don't have an account?",
    subscribe:        'Subscribe to get started',
    dashboard:        'Dashboard',
    inbox:            'Inbox',
    reviews:          'Reviews',
    qr:               'QR Code',
    settings:         'Settings',
    totalFeedback:    'Total Feedback',
    avgRating:        'Avg Rating',
    complaints:       'Complaints',
    noFeedback:       'No feedback yet. Share your QR code to get started.',
    recentFeedback:   'Recent Feedback',
    downloadQR:       'Download QR',
    viewReviews:      'View Reviews',
    saveChanges:      'Save Changes',
    businessInfo:     'Business Info',
    notifications:    'Notifications',
    subscription:     'Subscription',
    account:          'Account',
    // Feedback form
    rateExperience:   'How was your experience?',
    shareThoughts:    'Share your thoughts (optional)',
    yourName:         'Your name (optional)',
    yourPhone:        'Phone number (optional)',
    submitFeedback:   'Submit Feedback',
    thankYou:         'Thank you for your feedback!',
    thankYouSub:      'Your response helps us serve you better.',
    shareOnGoogle:    'Would you like to share this publicly?',
    shareOnGoogleBtn: 'Share on Google',
    maybeNext:        'Maybe next time',
  },
  te: {
    greeting:         (name) => `నమస్కారం, ${name} 🙏`,
    tagline:          'స్థానిక వ్యాపారాల కోసం రెప్యుటేషన్ మేనేజ్‌మెంట్',
    signIn:           'సైన్ ఇన్',
    signOut:          'సైన్ అవుట్',
    getStarted:       'ప్రారంభించండి',
    email:            'ఇమెయిల్ చిరునామా',
    password:         'పాస్‌వర్డ్',
    noAccount:        'అకౌంట్ లేదా?',
    subscribe:        'ప్రారంభించడానికి సబ్‌స్క్రైబ్ చేయండి',
    dashboard:        'డ్యాష్‌బోర్డ్',
    inbox:            'ఇన్‌బాక్స్',
    reviews:          'రివ్యూలు',
    qr:               'QR కోడ్',
    settings:         'సెట్టింగ్స్',
    totalFeedback:    'మొత్తం ఫీడ్‌బ్యాక్',
    avgRating:        'సగటు రేటింగ్',
    complaints:       'ఫిర్యాదులు',
    noFeedback:       'ఇంకా ఫీడ్‌బ్యాక్ లేదు. మీ QR కోడ్ షేర్ చేయండి.',
    recentFeedback:   'ఇటీవలి ఫీడ్‌బ్యాక్',
    downloadQR:       'PNG డౌన్‌లోడ్',
    viewReviews:      'రివ్యూలు చూడండి',
    saveChanges:      'మార్పులు సేవ్ చేయండి',
    businessInfo:     'వ్యాపార సమాచారం',
    notifications:    'నోటిఫికేషన్లు',
    subscription:     'సబ్‌స్క్రిప్షన్',
    account:          'అకౌంట్',
    rateExperience:   'మీ అనుభవం ఎలా ఉంది?',
    shareThoughts:    'మీ అభిప్రాయం చెప్పండి (ఐచ్ఛికం)',
    yourName:         'మీ పేరు (ఐచ్ఛికం)',
    yourPhone:        'ఫోన్ నంబర్ (ఐచ్ఛికం)',
    submitFeedback:   'ఫీడ్‌బ్యాక్ సమర్పించండి',
    thankYou:         'మీ ఫీడ్‌బ్యాక్‌కు ధన్యవాదాలు!',
    thankYouSub:      'మీ స్పందన మాకు మెరుగుపడటానికి సహాయపడుతుంది.',
    shareOnGoogle:    'దీన్ని పబ్లిక్‌గా షేర్ చేయాలనుకుంటున్నారా?',
    shareOnGoogleBtn: 'Google లో షేర్ చేయండి',
    maybeNext:        'తర్వాత చూద్దాం',
  },
  kn: {
    greeting:         (name) => `ನಮಸ್ಕಾರ, ${name} 🙏`,
    tagline:          'ಸ್ಥಳೀಯ ವ್ಯವಹಾರಗಳಿಗಾಗಿ ರೆಪ್ಯುಟೇಶನ್ ಮ್ಯಾನೇಜ್‌ಮೆಂಟ್',
    signIn:           'ಸೈನ್ ಇನ್',
    signOut:          'ಸೈನ್ ಔಟ್',
    getStarted:       'ಪ್ರಾರಂಭಿಸಿ',
    email:            'ಇಮೇಲ್ ವಿಳಾಸ',
    password:         'ಪಾಸ್‌ವರ್ಡ್',
    noAccount:        'ಖಾತೆ ಇಲ್ಲವೇ?',
    subscribe:        'ಪ್ರಾರಂಭಿಸಲು ಸಬ್‌ಸ್ಕ್ರೈಬ್ ಮಾಡಿ',
    dashboard:        'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    inbox:            'ಇನ್‌ಬಾಕ್ಸ್',
    reviews:          'ವಿಮರ್ಶೆಗಳು',
    qr:               'QR ಕೋಡ್',
    settings:         'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    totalFeedback:    'ಒಟ್ಟು ಫೀಡ್‌ಬ್ಯಾಕ್',
    avgRating:        'ಸರಾಸರಿ ರೇಟಿಂಗ್',
    complaints:       'ದೂರುಗಳು',
    noFeedback:       'ಇನ್ನೂ ಫೀಡ್‌ಬ್ಯಾಕ್ ಇಲ್ಲ. ನಿಮ್ಮ QR ಕೋಡ್ ಹಂಚಿಕೊಳ್ಳಿ.',
    recentFeedback:   'ಇತ್ತೀಚಿನ ಫೀಡ್‌ಬ್ಯಾಕ್',
    downloadQR:       'PNG ಡೌನ್‌ಲೋಡ್',
    viewReviews:      'ವಿಮರ್ಶೆಗಳನ್ನು ನೋಡಿ',
    saveChanges:      'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    businessInfo:     'ವ್ಯವಹಾರ ಮಾಹಿತಿ',
    notifications:    'ಅಧಿಸೂಚನೆಗಳು',
    subscription:     'ಸದಸ್ಯತ್ವ',
    account:          'ಖಾತೆ',
    rateExperience:   'ನಿಮ್ಮ ಅನುಭವ ಹೇಗಿತ್ತು?',
    shareThoughts:    'ನಿಮ್ಮ ಅಭಿಪ್ರಾಯ ಹಂಚಿಕೊಳ್ಳಿ (ಐಚ್ಛಿಕ)',
    yourName:         'ನಿಮ್ಮ ಹೆಸರು (ಐಚ್ಛಿಕ)',
    yourPhone:        'ಫೋನ್ ನಂಬರ್ (ಐಚ್ಛಿಕ)',
    submitFeedback:   'ಫೀಡ್‌ಬ್ಯಾಕ್ ಸಲ್ಲಿಸಿ',
    thankYou:         'ನಿಮ್ಮ ಫೀಡ್‌ಬ್ಯಾಕ್‌ಗೆ ಧನ್ಯವಾದಗಳು!',
    thankYouSub:      'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ ನಮಗೆ ಸುಧಾರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    shareOnGoogle:    'ಇದನ್ನು ಸಾರ್ವಜನಿಕವಾಗಿ ಹಂಚಿಕೊಳ್ಳಲು ಬಯಸುತ್ತೀರಾ?',
    shareOnGoogleBtn: 'Google ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ',
    maybeNext:        'ಮುಂದೆ ನೋಡೋಣ',
  },
  ta: {
    greeting:         (name) => `நமஸ்காரம், ${name} 🙏`,
    tagline:          'உள்ளூர் வணிகங்களுக்கான நற்பெயர் மேலாண்மை',
    signIn:           'உள்நுழை',
    signOut:          'வெளியேறு',
    getStarted:       'தொடங்கு',
    email:            'மின்னஞ்சல் முகவரி',
    password:         'கடவுச்சொல்',
    noAccount:        'கணக்கு இல்லையா?',
    subscribe:        'தொடங்க சந்தா செலுத்துங்கள்',
    dashboard:        'டாஷ்போர்டு',
    inbox:            'இன்பாக்ஸ்',
    reviews:          'மதிப்புரைகள்',
    qr:               'QR குறியீடு',
    settings:         'அமைப்புகள்',
    totalFeedback:    'மொத்த கருத்து',
    avgRating:        'சராசரி மதிப்பீடு',
    complaints:       'புகார்கள்',
    noFeedback:       'இன்னும் கருத்து இல்லை. உங்கள் QR குறியீட்டை பகிருங்கள்.',
    recentFeedback:   'சமீபத்திய கருத்து',
    downloadQR:       'PNG பதிவிறக்கம்',
    viewReviews:      'மதிப்புரைகளை காண்க',
    saveChanges:      'மாற்றங்களை சேமி',
    businessInfo:     'வணிக தகவல்',
    notifications:    'அறிவிப்புகள்',
    subscription:     'சந்தா',
    account:          'கணக்கு',
    rateExperience:   'உங்கள் அனுபவம் எப்படி இருந்தது?',
    shareThoughts:    'உங்கள் கருத்தை பகிருங்கள் (விருப்பத்தேர்வு)',
    yourName:         'உங்கள் பெயர் (விருப்பத்தேர்வு)',
    yourPhone:        'தொலைபேசி எண் (விருப்பத்தேர்வு)',
    submitFeedback:   'கருத்தை சமர்ப்பி',
    thankYou:         'உங்கள் கருத்துக்கு நன்றி!',
    thankYouSub:      'உங்கள் பதில் எங்களை மேம்படுத்த உதவுகிறது.',
    shareOnGoogle:    'இதை பொதுவில் பகிர விரும்புகிறீர்களா?',
    shareOnGoogleBtn: 'Google இல் பகிர்',
    maybeNext:        'அடுத்த முறை பார்க்கலாம்',
  },
  hi: {
    greeting:         (name) => `नमस्कारम्, ${name} 🙏`,
    tagline:          'स्थानीय व्यवसायों के लिए प्रतिष्ठा प्रबंधन',
    signIn:           'साइन इन',
    signOut:          'साइन आउट',
    getStarted:       'शुरू करें',
    email:            'ईमेल पता',
    password:         'पासवर्ड',
    noAccount:        'खाता नहीं है?',
    subscribe:        'शुरू करने के लिए सब्सक्राइब करें',
    dashboard:        'डैशबोर्ड',
    inbox:            'इनबॉक्स',
    reviews:          'समीक्षाएं',
    qr:               'QR कोड',
    settings:         'सेटिंग्स',
    totalFeedback:    'कुल फीडबैक',
    avgRating:        'औसत रेटिंग',
    complaints:       'शिकायतें',
    noFeedback:       'अभी तक कोई फीडबैक नहीं। अपना QR कोड शेयर करें।',
    recentFeedback:   'हालिया फीडबैक',
    downloadQR:       'PNG डाउनलोड',
    viewReviews:      'समीक्षाएं देखें',
    saveChanges:      'बदलाव सहेजें',
    businessInfo:     'व्यवसाय जानकारी',
    notifications:    'सूचनाएं',
    subscription:     'सदस्यता',
    account:          'खाता',
    rateExperience:   'आपका अनुभव कैसा रहा?',
    shareThoughts:    'अपने विचार साझा करें (वैकल्पिक)',
    yourName:         'आपका नाम (वैकल्पिक)',
    yourPhone:        'फोन नंबर (वैकल्पिक)',
    submitFeedback:   'फीडबैक सबमिट करें',
    thankYou:         'आपके फीडबैक के लिए धन्यवाद!',
    thankYouSub:      'आपकी प्रतिक्रिया हमें बेहतर बनाने में मदद करती है।',
    shareOnGoogle:    'क्या आप इसे सार्वजनिक रूप से साझा करना चाहते हैं?',
    shareOnGoogleBtn: 'Google पर साझा करें',
    maybeNext:        'अगली बार देखेंगे',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = STRINGS[lang]
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLang must be used within LanguageProvider')
  return ctx
}
